name: projectmanagementstmiktime
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  email_validator: ^3.0.0
  flutter_svg: ^2.0.17
  intl: ^0.18.1
  dio: ^5.8.0+1
  shared_preferences: ^2.5.2
  quickalert: ^1.1.0
  skeletonizer: ^1.4.3
  flutter_otp_text_field: ^1.1.1
  file_picker: ^10.1.2
  path_provider: ^2.1.5   # untuk akses direktori aplikasi
  open_file: ^3.5.10
  url_launcher: ^6.1.10
  dotted_border: ^2.0.0+3
  permission_handler: ^11.1.0
  flutter_local_notifications: ^19.1.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.2
  firebase_messaging: ^14.7.8
  awesome_notifications: ^0.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/

  # fonts:
    # - family: Helvetica
    #   fonts:
        # - asset: fonts/Helvetica-Bold.ttf
        # - asset: fonts/Helvetica-BoldOblique.ttf
        # - asset: fonts/helvetica-light-587ebe5a59211.ttf
        # - asset: fonts/Helvetica-Oblique.ttf
        # - asset: fonts/Helvetica.ttf
