name: projectmanagementstmiktime
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  email_validator: ^3.0.0
  flutter_svg: ^2.0.17
  intl: ^0.20.2
  dio: ^5.8.0+1
  shared_preferences: ^2.5.2
  quickalert: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

  # fonts:
    # - family: Helvetica
    #   fonts:
        # - asset: fonts/Helvetica-Bold.ttf
        # - asset: fonts/Helvetica-BoldOblique.ttf
        # - asset: fonts/helvetica-light-587ebe5a59211.ttf
        # - asset: fonts/Helvetica-Oblique.ttf
        # - asset: fonts/Helvetica.ttf
