name: projectmanagementstmiktime
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.0.5
  email_validator: ^2.1.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

fonts:
    # - family: Helvetica
    #   fonts:
        # - asset: fonts/Helvetica-Bold.ttf
        # - asset: fonts/Helvetica-BoldOblique.ttf
        # - asset: fonts/helvetica-light-587ebe5a59211.ttf
        # - asset: fonts/Helvetica-Oblique.ttf
        # - asset: fonts/Helvetica.ttf