// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvy3Y3OMekvi940naPT4C3gx_aH3h8RUc',
    appId: '1:714430274137:web:d5d36dfcf4971529da6f48',
    messagingSenderId: '714430274137',
    projectId: 'projectmanagementtime',
    authDomain: 'projectmanagementtime.firebaseapp.com',
    storageBucket: 'projectmanagementtime.firebasestorage.app',
    measurementId: 'G-D8DNK80RR3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTNcaPH2WkX98VVgPmdMTpmCagxZI04R0',
    appId: '1:714430274137:android:79069ba3a012709eda6f48',
    messagingSenderId: '714430274137',
    projectId: 'projectmanagementtime',
    storageBucket: 'projectmanagementtime.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGnUK44o_sRs9_CdgqF5finMe1J-q2EIY',
    appId: '1:714430274137:ios:1c2190cd4b13df9bda6f48',
    messagingSenderId: '714430274137',
    projectId: 'projectmanagementtime',
    storageBucket: 'projectmanagementtime.firebasestorage.app',
    iosBundleId: 'com.example.projectmanagementstmiktime',
  );
}
